### ISSUE TITLE
Kill job command client error

### ISSUE THREAD

**Issue by SuchithArodi** [aurora-scheduler/australis#21]
In the latest version of australis `b21211552f61be84cd2185fa46172e67748b2964`, kill job command is not working. 
Kill job command works fine for the commit hash `9fa6edaa3e98ed386bdaabe1c493eff21e6efe80` 

$ ./australis kill job -z <ip> -u <username> -p <password> -e <env> -r <role> -n <name> -l debug
INFO[0000] Scheduler URL from ZK:  http://localhost.test:8081 
INFO[0000] gorealis clientConfig url: http://localhost.test8081/api 
INFO[0000] Killing job [Env: <> Role: <> Name:<>] 
INFO[0000] Client Error: Response buffer is nil.        
INFO[0000] Re-establishing Connection to Aurora         
INFO[0000] Scheduler URL from ZK:  http://localhost.test:8081 
INFO[0000] gorealis clientConfig url: http://localhost.test:8081/api 
INFO[0000] A retryable error occurred during thrift call, backing off for 10.450946323s before retry 1 
INFO[0011] Client Error: Response buffer is nil.        
INFO[0011] Re-establishing Connection to Aurora         
INFO[0011] Scheduler URL from ZK:  http://localhost.test:8081 
INFO[0011] gorealis clientConfig url: http://localhost.test:8081/api 
INFO[0011] retried this thrift call 2 time(s)           
FATA[0011] error sending Kill command to Aurora Scheduler: ran out of retries, including latest error: Response buffer is nil.

**Comment by ridv** [comment]
Fixed by https://github.com/aurora-scheduler/australis/commit/30a5136b24f4ff65c20a297cd0483382c2b330b9
